### ISSUE TITLE
Error: TRMM.vrt file does not exist

### ISSUE THREAD

**Issue by manishecol** [cvitolo/r_hddtools#1] opened 2016-05-23 17:46 UTC
Hi,
Im trying to download the 3B42_v7 3 hourly data sing the TRMM function. The files get downloaded, however, I keep getting the following error:
"`D:\analysis_ravi\TRMM downlaod\kas_2016\TRMM.vrt' does not exist in the file system,
and is not recognised as a supported dataset name.

In addition: There were 17 warnings (use warnings() to see them)
Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create a RasterLayer object from this file. (file does not exist)"

tried testing with 3B43_v7 dataset as well and same error.
Im using r 3.2.5 on windows 7 64-bit OS.

Any help would be greatly appreciated..

Regards
Manish
PhD Student
ATREE, India

**Comment by cvitolo** [comment] 2016-09-05 21:09
Hi Manish, I have recently updated the package and added tests for windows as well. Do you mind to install the latest version of hddtools and let me know if the problem is fixed now? Thanks

**Comment by manishecol** [comment] 2016-09-06 11:00
Hi Claudia,

Thanks a lot for the update. I tried using the updated packages and the 
error persists. While using the inbuilt TRMM function, I got following 
error:

Error in TRMM(fileLocation = "D:/analysis_ravi/TRMM download/knp_2016/", 
: unused arguments (fileLocation = "D:/analysis_ravi/TRMM 
download/knp_2016/", url = 
"ftp://disc2.nascom.nasa.gov/data/TRMM/Gridded/", year = 2015)

So i tried using the function code from github and it was successful in 
downloading the TRMM data (even for 3B42v7 product) but got error again 
with the TRMM.vrt file:
"`D:\analysis_ravi\TRMM downlaod\knp_2016\TRMM.vrt' does not exist in 
the file system,
and is not recognised as a supported dataset name.

In addition: There were 17 warnings (use warnings() to see them)
Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) :
Cannot create a RasterLayer object from this file. (file does not exist)"

Please let me know if you can access 3B42v7 product on windows with codes.

Again.. thanks for the help.

Regards
Manish

**Comment by cvitolo** [comment] 2017-01-16 19:12
This is now fixed.

**Closed as completed by cvitolo** 2017-01-16 19:12 UTC
